### ISSUE TITLE
Seed DB on startup 

### ISSUE THREAD

**Issue by szeckirjr** [SENG499-Company-4/Backend#6]
Find and transform the data needed into the required schema, and then upload historical data into DB

**Comment by keithradford** [comment]
Bellow is a set of steps of how I envision this task going. Depending on complexity each step could be broken into separate PRs but getting the first two done is a good first step.
- [ ] Follow this guide to get set up https://www.prisma.io/docs/guides/database/seed-database
- [ ] Seed DB with some user accounts (I'd say roughly 10, at least 1 admin and the rest users)
- [ ] Seed DB with historical class data (Classes + meeting times going back a couple of years. A lot of the info can be random but what we do have access to can hopefully be piped in to the DB)
- [ ] Randomize professor settings and preferences and tie them to users + courses which should be in the DB if the 2 steps above are completed
